import React, { createContext, useContext, useState } from "react";

type Language = "en" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    home: "Home",
    about: "About",
    services: "Services",
    projects: "Projects",
    caseStudies: "Case Studies",
    contact: "Contact",
    getStarted: "Get Started",
    viewProjects: "View Projects",
    aboutMe: "About Me",
    bio: "Amateur Vibe coder specializing in Python automation, Telegram bots, API integrations, and security research. I create innovative solutions ranging from AI-powered bots to security tools for educational purposes.",
    languages: "Languages",
    sinhala: "Sinhala - Native",
    english: "English - B2",
    german: "German - A1",
    services_title: "Services",
    telegramBot: "Telegram Bot Development",
    telegramBotDesc: "Creating intelligent Telegram bots with AI integration, advanced moderation, and automation features for various use cases.",
    pythonAutomation: "Python Automation",
    pythonAutomationDesc: "Building powerful automation scripts and tools using Python for data processing, web scraping, and workflow optimization.",
    apiIntegration: "API Integration",
    apiIntegrationDesc: "Expert integration with various APIs including TMDB, YouTube, Weather APIs, and custom REST API development.",
    securityResearch: "Security Research",
    securityResearchDesc: "Educational security tools and research projects for authorized testing and learning purposes only.",
    machineLearning: "Machine Learning",
    machineLearningDesc: "ML model development and deployment using FastAPI, Streamlit, and popular frameworks for intelligent applications.",
    dataAnalysis: "Data Analysis",
    dataAnalysisDesc: "Creating comprehensive dashboards and analytical tools for data visualization and business intelligence.",
    projects_title: "Projects",
    inProgress: "In Progress",
    completed: "Completed",
    getInTouch: "Get In Touch",
    name: "Name",
    email: "Email",
    message: "Message",
    sendMessage: "Send Message",
    sending: "Sending...",
    messageSent: "Message sent successfully! I will get back to you soon.",
    messageError: "Failed to send message. Please try again.",
    allRightsReserved: "All rights reserved",
    colombo: "Colombo, Sri Lanka",
    caseStudiesPage: "Case Studies",
    caseStudiesDesc: "Explore detailed case studies of my most impactful projects, showcasing challenges solved, solutions implemented, and results achieved.",
    backToCaseStudies: "Back to Case Studies",
    backToHome: "Back to Home",
    overview: "Overview",
    challenge: "Challenge",
    solution: "Solution",
    results: "Results",
    technologies: "Technologies",
    readMore: "Read More",
    backToAll: "Back to All Case Studies",
    helloIm: "Hello I'm",
    softwareDeveloper: "Security Researcher, Network Enthusiasts & Software Developer",
    aboutText1: "I'm a passionate software developer from Colombo with expertise in Python development, bot creation, API integrations, and security research. My work focuses on building practical automation tools and educational security projects.",
    aboutText2: "I specialize in creating Telegram bots with advanced features, working with various APIs (TMDB, YouTube, Weather), and developing tools for security research and educational purposes. All my security-related projects are strictly for authorized testing and learning.",
    carbonFootprintTitle: "Carbon Footprint Calculator",
    carbonFootprintDesc: "An innovative application to calculate and track carbon emissions. Helps users understand their environmental impact and provides actionable insights for reducing carbon footprint.",
    bluetoothMeshTitle: "Bluetooth Mesh Network",
    bluetoothMeshDesc: "Developing a robust Bluetooth mesh networking solution for IoT devices. Enables seamless device-to-device communication and creates scalable smart device networks.",
    aiGroupBotTitle: "AI Group Manager Bot",
    aiGroupBotDesc: "A professional, AI-powered Telegram group management bot with advanced moderation features. MIT Licensed. Built with intelligent automation for group administration.",
    movieBotTitle: "Movie & Series Recommendation Bot",
    movieBotDesc: "A fully functional Telegram bot that recommends movies and TV series using the TMDB API. Features genre-based recommendations, search, trending content, and personal watchlist.",
    linkToBotTitle: "Link to File Telegram Bot",
    linkToBotDesc: "Feature-rich Telegram bot for downloading files from various sources with specialized YouTube support, audio extraction, and animated progress tracking. MIT Licensed.",
    keyloggerTitle: "Keylogger (Educational)",
    keyloggerDesc: "Cross-platform keylogging solution for educational and authorized security testing purposes only. Demonstrates security concepts for learning.",
    sopProjectTitle: "SOP Project",
    sopProjectDesc: "Travel advisory and Open Weather API integration project. Testing various API functionalities for real-world applications.",
    wineQualityTitle: "Wine Quality Prediction",
    wineQualityDesc: "Machine learning application for predicting wine quality using data analysis and ML algorithms. Built with Jupyter Notebook.",
    viewOnGithub: "View on GitHub",
    certifications: "Certifications",
    completedCertifications: "Completed Certifications",
    inProgressCertifications: "In Progress Certifications",
    introCybersecurity: "Introduction to Cybersecurity",
    itCustomerSupport: "IT Customer Support Basics",
    networkingBasics: "Networking Basics",
    ethicalHacker: "Ethical Hacker",
    introIoT: "Introduction to IoT and Digital Transformation",
    ciscoNetworkingAcademy: "Cisco Networking Academy",
  },
  de: {
    home: "Startseite",
    about: "Über mich",
    services: "Dienstleistungen",
    projects: "Projekte",
    caseStudies: "Fallstudien",
    contact: "Kontakt",
    getStarted: "Erste Schritte",
    viewProjects: "Projekte anzeigen",
    aboutMe: "Über mich",
    bio: "Amateur Vibe-Coder mit Spezialisierung auf Python-Automatisierung, Telegram-Bots, API-Integrationen und Sicherheitsforschung. Ich entwickle innovative Lösungen von KI-gesteuerten Bots bis zu Sicherheitswerkzeugen für Bildungszwecke.",
    languages: "Sprachen",
    sinhala: "Singhalesisch - Muttersprache",
    english: "Englisch - B2",
    german: "Deutsch - A1",
    services_title: "Dienstleistungen",
    telegramBot: "Telegram-Bot-Entwicklung",
    telegramBotDesc: "Erstellung intelligenter Telegram-Bots mit KI-Integration, fortgeschrittener Moderation und Automatisierungsfunktionen.",
    pythonAutomation: "Python-Automatisierung",
    pythonAutomationDesc: "Entwicklung leistungsstarker Automatisierungsskripte und Tools mit Python für Datenverarbeitung, Web-Scraping und Workflow-Optimierung.",
    apiIntegration: "API-Integration",
    apiIntegrationDesc: "Expertenkompetenz in der Integration verschiedener APIs einschließlich TMDB, YouTube, Wetter-APIs und benutzerdefinierter REST-API-Entwicklung.",
    securityResearch: "Sicherheitsforschung",
    securityResearchDesc: "Bildungssicherheitswerkzeuge und Forschungsprojekte für autorisierte Tests und Lernzwecke.",
    machineLearning: "Maschinelles Lernen",
    machineLearningDesc: "ML-Modellentwicklung und -bereitstellung mit FastAPI, Streamlit und beliebten Frameworks für intelligente Anwendungen.",
    dataAnalysis: "Datenanalyse",
    dataAnalysisDesc: "Erstellung umfassender Dashboards und Analysetools zur Datenvisualisierung und Business Intelligence.",
    projects_title: "Projekte",
    inProgress: "In Bearbeitung",
    completed: "Abgeschlossen",
    getInTouch: "Kontakt aufnehmen",
    name: "Name",
    email: "E-Mail",
    message: "Nachricht",
    sendMessage: "Nachricht senden",
    sending: "Wird gesendet...",
    messageSent: "Nachricht erfolgreich versendet! Ich werde mich bald bei Ihnen melden.",
    messageError: "Fehler beim Senden der Nachricht. Bitte versuchen Sie es später erneut.",
    allRightsReserved: "Alle Rechte vorbehalten",
    colombo: "Colombo, Sri Lanka",
    caseStudiesPage: "Fallstudien",
    caseStudiesDesc: "Erkunden Sie detaillierte Fallstudien meiner einflussreichsten Projekte, die gelöste Herausforderungen, implementierte Lösungen und erzielte Ergebnisse zeigen.",
    backToCaseStudies: "Zurück zu den Fallstudien",
    backToHome: "Zurück zur Startseite",
    overview: "Übersicht",
    challenge: "Herausforderung",
    solution: "Lösung",
    results: "Ergebnisse",
    technologies: "Technologien",
    readMore: "Mehr erfahren",
    backToAll: "Zurück zu allen Fallstudien",
    helloIm: "Hallo, ich bin",
    carbonFootprintTitle: "Kohlenstoff-Fußabdruck-Rechner",
    carbonFootprintDesc: "Eine innovative Anwendung zur Berechnung und Verfolgung von Kohlenstoffemissionen. Hilft Benutzern, ihre Umweltauswirkungen zu verstehen und bietet umsetzbare Erkenntnisse zur Verringerung des Kohlenstoff-Fußabdrucks.",
    bluetoothMeshTitle: "Bluetooth-Mesh-Netzwerk",
    bluetoothMeshDesc: "Entwicklung einer robusten Bluetooth-Mesh-Netzwerklösung für IoT-Geräte. Ermöglicht nahtlose Gerät-zu-Gerät-Kommunikation und schafft skalierbare Smart-Device-Netzwerke.",
    aiGroupBotTitle: "KI-Gruppenverwaltungs-Bot",
    aiGroupBotDesc: "Ein professioneller, KI-gestützter Telegram-Gruppenverwaltungs-Bot mit erweiterten Moderationsfunktionen. MIT-lizenziert. Gebaut mit intelligenter Automatisierung für die Gruppenverwaltung.",
    movieBotTitle: "Film- und Serien-Empfehlungs-Bot",
    movieBotDesc: "Ein vollständig funktionsfähiger Telegram-Bot, der Filme und Fernsehserien mit der TMDB-API empfiehlt. Bietet genrebasierte Empfehlungen, Suche, Trending-Inhalte und persönliche Watchlist.",
    linkToBotTitle: "Link-zu-Datei-Telegram-Bot",
    linkToBotDesc: "Funktionsreicher Telegram-Bot zum Herunterladen von Dateien aus verschiedenen Quellen mit spezialisierter YouTube-Unterstützung, Audioextraktion und animiertem Fortschrittsverfolger. MIT-lizenziert.",
    keyloggerTitle: "Keylogger (Bildung)",
    keyloggerDesc: "Plattformübergreifende Keylogging-Lösung nur für Bildungs- und autorisierte Sicherheitstests. Demonstriert Sicherheitskonzepte zum Lernen.",
    sopProjectTitle: "SOP-Projekt",
    sopProjectDesc: "Reiseberatungs- und Open-Weather-API-Integrationsprojekt. Testen verschiedener API-Funktionalitäten für reale Anwendungen.",
    wineQualityTitle: "Weinqualitätsvorhersage",
    wineQualityDesc: "Machine-Learning-Anwendung zur Vorhersage der Weinqualität mit Datenanalyse und ML-Algorithmen. Erstellt mit Jupyter Notebook.",
    viewOnGithub: "Auf GitHub anzeigen",
    certifications: "Zertifizierungen",
    completedCertifications: "Abgeschlossene Zertifizierungen",
    inProgressCertifications: "Zertifizierungen in Bearbeitung",
    introCybersecurity: "Einführung in Cybersicherheit",
    itCustomerSupport: "Grundlagen des IT-Kundensupports",
    networkingBasics: "Netzwerk-Grundlagen",
    ethicalHacker: "Ethischer Hacker",
    introIoT: "Einführung in IoT und digitale Transformation",
    ciscoNetworkingAcademy: "Cisco Networking Academy",
    softwareDeveloper: "Softwareentwickler & Sicherheitsforscher",
    aboutText1: "Ich bin ein leidenschaftlicher Softwareentwickler aus Colombo mit Expertise in Python-Entwicklung, Bot-Erstellung, API-Integrationen und Sicherheitsforschung. Meine Arbeit konzentriert sich auf den Aufbau praktischer Automatisierungstools und Sicherheitsprojekte für Bildungszwecke.",
    aboutText2: "Ich spezialisiere mich auf die Erstellung von Telegram-Bots mit erweiterten Funktionen, die Arbeit mit verschiedenen APIs (TMDB, YouTube, Wetter) und die Entwicklung von Tools für Sicherheitsforschung und Bildungszwecke. Alle meine sicherheitsbezogenen Projekte sind streng für autorisierte Tests und Lernzwecke bestimmt.",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

export function useTranslation() {
  const { language } = useLanguage();
  return translations[language];
}
